# use an official Node.js runtime as the parent image because it comes pre installed with node.js
FROM node:16

# put the working directory in the container
WORKDIR /app

# copy package.json and package-lock.json
COPY package.json package-lock.json ./

# install necessary dependencies
RUN npm install

# copy the backend code
COPY . .

# expose port 5000
EXPOSE 5000

# run the server
CMD ["node", "server.js"]
