version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .  # Change this to the root directory
      dockerfile: src/Dockerfile-frontend  # Pointing to the Dockerfile inside src/
    ports:
      - "3000:3000"
    depends_on:
      - backend
