# Dockerfile-frontend 

# use the official Node.js image from Docker Hub
FROM node:16

# set the working directory in the container
WORKDIR /app

# copy the package.json and package-lock.json from the root to /app in the container
COPY ../package.json ../package-lock.json ./

# install dependencies
RUN npm install

# copy the rest of the files into the container
COPY . .

# expose port 3000
EXPOSE 3000

# start the app
CMD ["npm", "start"]
